version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysqlApiNestJs
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'apiNest'
      MYSQL_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'


